### PR TITLE
Add support for @FeignClient annotated interfaces.

### PR DESCRIPTION
**Pull request by tjuchniewicz**
- Autodetect content-type from params to support legacy services.

### CODE REVIEW

**Comment by tjuchniewicz** [comment]
Fixes https://github.com/spring-cloud/spring-cloud-netflix/issues/1274

**Comment by mwinkelmann** [comment]
Is it useful to add the dependency 
`<dependency>
<groupId>org.springframework</groupId>
<artifactId>spring-web</artifactId>
<scope>compile</scope>
</dependency>`
only for multipart support? I think it is not painful to convert it to a file before you do the call with feign!?

` String filePath = System.getProperty("java.io.tmpdir") + System.getProperty("file.separator") +
                photoFile.getOriginalFilename();
        File tempFile = new File(filePath);
        try {
            photoFile.transferTo(tempFile);
...`

Good pull request I think 👍

**Comment by tjuchniewicz** [comment]
@mwinkelmann This dependency is needed if we want to consume (existing) Spring MVC interfaces like this:

```java
@RequestMapping(value = "/multipart/upload" , method = RequestMethod.POST, 
                                produces = MediaType.APPLICATION_JSON_VALUE)
@ResponseBody String upload(@RequestPart MultipartFile file);
```
Encoder needs access to this class.

**Comment by mwinkelmann** [comment]
Yes also, r8! But is it meaningful to put this stuf also in this project? Wouldn't it be a case for a new library for spring-cloud-feign. Do you know what I mean? If I only use netflix-feign, nothing with spring etc. -> I don't want to have spring web in my classpath!

**Comment by tjuchniewicz** [comment]
I understand. Need to be discussed. What is better: two separate projects (code duplication) or one that supports two cases (more entries in classpath)...?

**Comment by mwinkelmann** [comment]
No code duplication! You can firstly make your fixes here how you have done it but without multipartfile and thereafter you can make a new project with this as dependency and build your MultipartSupportService etc... What do you think @xxlabaza

**Comment by tjuchniewicz** [comment]
I don't get it... If I can't use `MultipartFile` in this project so I need to reimplement FeignForm feature with `MultipartFile` support in other project...

**Comment by mwinkelmann** [comment]
No sure, but I think only some small parts needs to be refactored - like a list of "FileTypeHandler" in the processor which process the differences between the filetypes(multipart, file, byte, etc) - but it is only my view because I am not a friend to put every dependency in every extension.

**Comment by tjuchniewicz** [comment]
You are right. I just used less time consuming solution. My proposal is to create submodule (extension for Spring) in this project to have all code in one place.

**Comment by mwinkelmann** [comment]
Yes of course, it would be a good solution.

**Pull request merged**
